apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ro5b6ma9a-python
  janus-idp.io/tekton: ro5b6ma9a-python
  backstage.io/kubernetes-id: ro5b6ma9a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ro5b6ma9a-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
