apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ro5b6ma9a-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:dc8113171ceedd46380bcbb6517ad0f569e61e37@sha256:77c17b2cc3f0f556afb8c60f4f9d6db3b8e1eb119e3afdfffdc39095293e52f7
          name: container-image
